Bump org.springframework.boot:spring-boot-configuration-processor from 3.4.1 to 3.4.2 (#13)
Bumps
[org.springframework.boot:spring-boot-configuration-processor](https://github.com/spring-projects/spring-boot)
from 3.4.1 to 3.4.2.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/spring-projects/spring-boot/releases">org.springframework.boot:spring-boot-configuration-processor's
releases</a>.</em></p>
<blockquote>
<h2>v3.4.2</h2>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li>Property metadata for &quot;logging.structured.json.customizer&quot;
has incorrect type <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43916">#43916</a></li>
<li>GraylogExtendedLogFormatProperties throws NullPointerException when
only 'logging.structured.gelf.host' is specified <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/43863">#43863</a></li>
<li>Structured logging properties have no effect in a native image <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/43862">#43862</a></li>
<li>Docker Compose support for ClickHouse does not allow an empty
password when ALLOW_EMPTY_PASSWORD=yes <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/43790">#43790</a></li>
<li>docker compose ps now fails due to unknown --orphans flag with 2.23
or earlier <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43717">#43717</a></li>
<li>Build info timestamp is truncated to seconds <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43617">#43617</a></li>
<li>FileWatcher used for SSL reload does not support symlinks <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43604">#43604</a></li>
<li>BindableRuntimeHintsRegistrar should handle TypeNotPresentException
<a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43600">#43600</a></li>
<li>CapturedOutput is empty when using Log4J2 StatusLogger <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43578">#43578</a></li>
<li>Spring Boot 3.4 is not compatible with Gson 2.10 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43442">#43442</a></li>
<li>NoClassDefFoundError when using JUnit to test a Gradle 7.6.x app
that depends on spring-boot-actuator-autoconfigure but not on
org.junit.platform:junit-platform-launcher <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43340">#43340</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Document that the <code>@ConfigurationProperties</code> annotation
processor cannot generate description and defaultValue metadata for
external types <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43929">#43929</a></li>
<li>Fix description of management.metrics.graphql.autotime.enabled <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43905">#43905</a></li>
<li>Document 'base64:' prefix support <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43835">#43835</a></li>
<li>Document handling of <code>@Fallback</code> beans in
ConditionalOnSingleCandidate's javadoc <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/43826">#43826</a></li>
<li>Javadoc of DataSourceBuilder does not reference all supported types
<a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43732">#43732</a></li>
<li>Update OpenTelemetry section in Supported Monitoring Systems to
refer to OTLP instead <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43729">#43729</a></li>
<li>Consistently document the minimum supported versions of Gradle <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43725">#43725</a></li>
<li>Document that system libraries are a reason to customize the builder
and switch away from builder-jammy-java-tiny <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43716">#43716</a></li>
<li>Links to the Javadoc of Jakarta Messaging are invalid <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43662">#43662</a></li>
<li>Paragraph HTML tags are rendered as-is in Maven Plugin reference
documentation <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43623">#43623</a></li>
<li>Javadoc link for jakarta.xml.bind is invalid <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43607">#43607</a></li>
<li>Documentation still has references to 'layertools' <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43605">#43605</a></li>
<li>Javadoc of ConstructorBinding should not use markdown formatting <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43599">#43599</a></li>
<li>Managed Dependency Coordinates lists Spock and OkHttp dependencies
that are not managed <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43584">#43584</a></li>
</ul>
<h2>:hammer: Dependency Upgrades</h2>
<ul>
<li>Upgrade to ActiveMQ 6.1.5 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43791">#43791</a></li>
<li>Upgrade to Commons Codec 1.17.2 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43720">#43720</a></li>
<li>Upgrade to Couchbase Client 3.7.7 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43843">#43843</a></li>
<li>Upgrade to FreeMarker 2.3.34 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43721">#43721</a></li>
<li>Upgrade to Hibernate 6.6.5.Final <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43910">#43910</a></li>
<li>Upgrade to HttpCore5 5.3.2 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43792">#43792</a></li>
<li>Upgrade to Infinispan 15.0.12.Final <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43911">#43911</a></li>
<li>Upgrade to Jersey 3.1.10 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43793">#43793</a></li>
<li>Upgrade to jOOQ 3.19.18 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43844">#43844</a></li>
<li>Upgrade to Lettuce 6.4.2.RELEASE <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43609">#43609</a></li>
<li>Upgrade to Logback 1.5.16 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43715">#43715</a></li>
<li>Upgrade to Micrometer 1.14.3 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43745">#43745</a></li>
<li>Upgrade to Micrometer Tracing 1.4.2 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43746">#43746</a></li>
<li>Upgrade to Netty 4.1.117.Final <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43845">#43845</a></li>
<li>Upgrade to Postgresql 42.7.5 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43846">#43846</a></li>
<li>Upgrade to Pulsar 3.3.4 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/43912">#43912</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/f775945ef00ea34afa875c361cf6e34273b613fd"><code>f775945</code></a>
Release v3.4.2</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/068b9604198d999da6c16698816a43d45b5ba2bd"><code>068b960</code></a>
Merge branch '3.3.x' into 3.4.x</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/34c83539460078a35ad5ba3e1ba583ec0199ca1b"><code>34c8353</code></a>
Next development version (v3.3.9-SNAPSHOT)</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/f184e98b7834cc71def363dca1be1f6f490420c7"><code>f184e98</code></a>
Merge branch '3.3.x' into 3.4.x</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/390963fe7414ca025b07c4b1c0891451afbb60a6"><code>390963f</code></a>
Document when defaultValue and description cannot be extracted</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/ef82719ca847982d1f7eb0bdf1c8b644ae7adbcf"><code>ef82719</code></a>
Fix memory comparison in ProcessInfoTests</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/1e35a0b82d6667cc54b31d60eb47f0ae71a5500b"><code>1e35a0b</code></a>
Correct the type of logging.structured.json.customizer</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/24e40e8f8202744f477b4741e927b9f4d767ba5e"><code>24e40e8</code></a>
Upgrade to Spring Pulsar 1.2.2</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/30dd62adca4d7d1184005a24f7ac0e9d23e9f641"><code>30dd62a</code></a>
Merge branch '3.3.x' into 3.4.x</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/a3eaafbbea8f1120ed977f5da66cf483a304971b"><code>a3eaafb</code></a>
Upgrade to Spring Pulsar 1.1.8</li>
<li>Additional commits viewable in <a
href="https://github.com/spring-projects/spring-boot/compare/v3.4.1...v3.4.2">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.springframework.boot:spring-boot-configuration-processor&package-manager=maven&previous-version=3.4.1&new-version=3.4.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>